### PR TITLE
Laravel 11.x Compatibility

### PR DESCRIPTION
**Pull request by laravel-shift**
This is an automated pull request from [Shift](https://laravelshift.com) to update your package code and dependencies to be compatible with Laravel 11.x.

**Before merging**, you need to:

- Checkout the `l11-compatibility` branch
- Review **all** comments for additional changes
- Thoroughly test your package

If you do find an issue, please report it by commenting on this PR to help improve future automation.

### CODE REVIEW

**Comment by laravel-shift** [comment]
:warning: Shift detected GitHub Actions which run jobs using a version `matrix`. Shift attempted to [update your configuration](https://github.com/fourstacks/flexible-presenter/pull/42/commits/99b0b5fb83070a5e790ba1682612fdbfef72664c?w=1) for Laravel 11. However, you should review these changes to ensure the desired combination of versions are built for your package.

**Comment by peterthomson** [comment]
From what I can tell. This package is fine with Laravel 11 and we're actively using the package so keen to help review if needed.

**Comment by pgtruesdell** [comment]
Can confirm this pr is working as expected.

**Comment by fourstacks** [comment]
Hi, thanks for your patience.  Life's been a bit busy recently but I'll make an effort to review this and get a new version tagged this week

**Pull request merged**
